# -*- coding: utf-8 -*-
"""app

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1ai_TFOyacDMV38LLM3f67puCKixiA54Y
"""

import streamlit as st
import requests

st.title("News Summarization & Sentiment Analysis")

company_name = st.text_input("Enter Company Name", "")

if st.button("Fetch News"):
    with st.spinner("Fetching News..."):
        response = requests.get(f"http://127.0.0.1:8000/news/?company={company_name}")

        if response.status_code == 200:
            data = response.json()
            st.json(data)

            tts_response = requests.get(f"http://127.0.0.1:8000/tts/?company={company_name}")
            if tts_response.status_code == 200:
                st.audio("summary.mp3", format="audio/mp3")
        else:
            st.error("Failed to fetch news. Please try again.")